name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8 
  - plyfile
  - python=3.11.0 
  - pip=22.3.1
  - pytorch=2.0.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tqdm
  - numpy=1.26.4
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python==4.8.1.78 
    - joblib